#!/usr/bin/env python3
"""Regenerates the delta-download fixtures from client/tests/demo_server.delta_pair(): test/fixtures/delta_fixtures.h
for the C host tests, and, given Espressif's generator, test/fixtures/delta_espressif.patch for the client's
byte-for-byte test. Needs the client and detools (pip install ./client[diff]); CI only reads the output.

    python tools/make_delta_fixtures.py [--espressif-tool PATH/esp_delta_ota_patch_gen.py]
"""
import argparse
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "client"), str(ROOT / "client" / "tests")]
import demo_server              # noqa: E402  (after the path)
from udsota import delta        # noqa: E402


# One C array definition of data, 16 bytes a line.
def c_array(name, data):
    lines = ["    " + " ".join("0x%02x," % b for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    return "static const uint8_t %s[%d] = {\n%s\n};\n" % (name, len(data), "\n".join(lines))


# The patch Espressif's own generator writes for base -> new.
def espressif_patch(tool, base, new):
    with tempfile.TemporaryDirectory() as d:
        d = pathlib.Path(d)
        (d / "base.bin").write_bytes(base)
        (d / "new.bin").write_bytes(new)
        subprocess.run([sys.executable, str(tool), "create_patch", "--chip", "esp32s3", "--base_binary", "base.bin",
                        "--new_binary", "new.bin", "--patch_file_name", "esp.patch"], cwd=d, check=True)
        return (d / "esp.patch").read_bytes()


# Writes the fixtures; see the module docstring.
def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--espressif-tool", type=pathlib.Path, help="esp_delta_ota_patch_gen.py, to regenerate "
                    "test/fixtures/delta_espressif.patch and check the client's 0x20 patch matches it")
    args = ap.parse_args()
    base, new = demo_server.delta_pair()
    p20 = delta.make_patch(base, new, "heatshrink")
    pnone = delta.make_patch(base, new, "none")
    p30 = delta.deflate(pnone)
    if args.espressif_tool is not None:
        esp = espressif_patch(args.espressif_tool, base, new)
        if esp != p20:
            sys.exit("the client's 0x20 patch differs from Espressif's generator's")
        (ROOT / "test" / "fixtures" / "delta_espressif.patch").write_bytes(esp)
    body = [
        "/* Generated by tools/make_delta_fixtures.py from client/tests/demo_server.delta_pair(); do not edit. A base\n"
        " * and a new demo image (fake_ota_build_image's layout: one segment, checksum, appended SHA-256) and the\n"
        " * patches between them in esp_delta_ota's format: DELTA_P20 (heatshrink, what DFI 0x20 carries, byte for byte\n"
        " * what Espressif's esp_delta_ota_patch_gen.py writes), DELTA_PNONE (uncompressed) and DELTA_P30 (DELTA_PNONE\n"
        " * as raw DEFLATE, what DFI 0x30 carries). DELTA_BASE_HASH is the base's appended SHA-256. */\n",
        "#pragma once\n#include <stdint.h>\n\n",
        c_array("DELTA_BASE", base), c_array("DELTA_NEW", new), c_array("DELTA_BASE_HASH", delta.validation_hash(base)),
        c_array("DELTA_P20", p20), c_array("DELTA_PNONE", pnone), c_array("DELTA_P30", p30),
    ]
    (ROOT / "test" / "fixtures" / "delta_fixtures.h").write_text("".join(body[:2]) + "\n".join(body[2:]))
    print("base %d, new %d; 0x20 patch %d, uncompressed %d, 0x30 %d bytes" % (len(base), len(new), len(p20),
                                                                             len(pnone), len(p30)))


if __name__ == "__main__":
    main()
